module wrap;

    initial begin

        // This was generated by running the original through VCS.

        $display("                   0 01101 01101");
        $display("                  10 11101 11101");

        $display("                  20 01101 01101");
        $display("                  30 11101 11101");

        $display("                  40 01101 01101");
        $display("                  50 11101 11101");

        $display("                  60 01101 01101 {011 01} 01101 {01 101}");
        $display("                  70 11001 11001 {110 01} 11001 {11 001}");
        $display("                  80 01110 01110 {011 10} 01110 {01 110}");
        $display("                  90 01010 01010 {010 10} 01010 {01 010}");
        $display("                 110 11010 11010 {110 10} 11010 {11 010}");
        $display("                 120 11101 11101 {111 01} 11101 {11 101}");

        #130;

    end

endmodule
